export const allProducts = [
      {
            id: 1,
            name: "Ps4 DVD Game FIFA 18 Gold Edition",
            category: "accessories",
            subCategory: "sports games",
            price: 66.98,
            stocks: 5,
            description: "Physical DVD ROM, Comes with 6 DVDs for Installation, Before purchase please check publisher website for minimum requirement of PC",
            image: "images/ps4-dvd.jpg",
      },
      {
            id: 2,
            name: "PS4 Game Call Of Duty WWII",
            category: "accessories",
            subCategory: "gaming tools",
            price: 77.99,
            stocks: 10,
            description: "Physical DVD ROM, Comes with 6 DVDs for Installation, Before purchase please check publisher website for minimum requirement of PC",
            image: "images/ps3gamegran.jpg",
      },
      {
            id: 3,
            name: "Nike Zoom Running Shoes Size 33 Red",
            category: "baby & kids",
            subCategory: "shoes & fashion",
            price: 164.44,
            stocks: 10,
            description: "Call of Duty returns to its historical roots with Call of Duty: World War II, a blockbuster experience from Sledgehammer Games. From the beaches of Normandy to the Hürtgen Forest, experience a dramatic story highlighting some of the most dramatic and iconic moments of World War II as a young soldier who is facing the unforgiving reality of war alongside his brothers in arms.",
            image: "images/nike-zoom-running.jpg",
      },
      {
            id: 4,
            name: "XboxOne Game Wars Battlefront",
            category: "accessories",
            subCategory: "gaming tools",
            price: 66.99,
            stocks: 15,
            description: "Embark on an endless Star Wars action experience from the bestselling Star Wars HD videogame franchise of all time. Rush through waves of enemies on Starkiller Base with the power of your lightsaber in your hands. Storm through the jungle canopy of a hidden Rebel base on Yavin 4 with your fellow troopers, dispensing firepower from AT-STs.",
            image: "images/xboxone.jpg",
      },
      {
            id: 5,
            name: "Russell Hobbs Kettle Premium",
            category: "kitchen wears",
            price: 73.99,
            stocks: 30,
            description: "A classic and cool looking appliance like this can be a great addition to any modern kitchen. Material This kettle features a stainless steel body which makes it rust-resistant, sturdy and durable.",
            image: "images/kettle.jpg",
      },
      {
            id: 6,
            name: "PlaySation 4 Pro 1TB Black Edition",
            category: "accessories",
            subCategory: "gaming tools",
            price: 650.89,
            stocks: 5,
            description: "Take play to the next level with PS4 Pro: See every detail explode into life with 4K gaming and entertainment, experience faster, smoother frame rates and more powerful gaming performance and enjoy richer, more vibrant colours with HDR technology.",
            image: "images/ps41pro1tb.jpg",
      },
      {
            id: 7,
            name: "Xbox One Lunar White Controller",
            category: "baby & kids",
            subCategory: "toys & media",
            price: 60.99,
            stocks: 20,
            description: "Experience the enhanced comfort and feel of the new Xbox Controller, featuring a sleek, streamlined design and textured grip. Enjoy custom button mapping and up to twice the wireless range. Plug in any compatible headset with the 3.5mm stereo headset jack.Play your favorite games on Windows 10 PCs, tabconsts and phones. Button mapping available via Xbox Accessories app. Range compared to previous controllers with the Xbox One S.",
            image: "images/mx-1.jpg",
      },
      {
            id: 8,
            name: "Pampers Premium Dry Care Pants",
            category: "baby & kids",
            subCategory: "diapers",
            price: 10.99,
            stocks: 70,
            description: "Pampers premium dry care pants style diapers are designed to give your baby our best skin protection. Made from silky soft materials, these new pants style diapers are superior to ordinary pants and protect your baby’s precious skin. They come with 3 absorbing channels that distribute wetness evenly and lock it away better to keep your baby dry and comfortable from the very first touch.",
            image: "images/pampers-premium.jpg",
      },
      {
            id: 9,
            name: "[New] Huggis Ultra pants Gold Size M 6 to 12kg for girls",
            category: "baby & kids",
            subCategory: "diapers",
            price: 20.99,
            stocks: 50,
            description: "Huggis Ultra pants Gold diapers have 3 revolutionary extra absorb channels, that help distribute wetness evenly throughout the pants diapers, so wetness doesn’t collect in one place. Their magic gel layer locks wetness inside and offers up to 12 hours of dryness to help your baby sleep soundly all night.",
            image: "images/pampers.jpg",
      },
      {
            id: 10,
            name: "Samsung Galaxy Note 8 Blue",
            category: "accessories",
            subCategory: "android phones",
            price: 785.99,
            stocks: 5,
            description: "The new Galaxy Note 8 Blue is for those who romance speed. Experience seamless and smooth multitasking, powered by 4 GB RAM and a 1.6 GHz, Octa-Core, Exynos 7870 processor. And with 64 GB internal memory, you have enough space to store more without the worry of running out of memory.",
            image: "images/note8-1.jpg",
      },
      {
            id: 11,
            name: "Adidas Mens SG Boots Red",
            category: "baby & kids",
            subCategory: "shoes & fashion",
            price: 110.99,
            stocks: 30,
            description: "Uniquely stylish and trendy adidas Ace 17.4 FxG shoes for men. The Soft, lightweight material is shaped to your foot for ultimate ball control. Flexible traction configured with studs for superior ball control on firm ground, artificial grass and hard ground.",
            image: "images/adidasbot-1.jpg",
      },
      {
            id: 12,
            name: "Panasonic LED TV 32 inch Sliver",
            category: "home living",
            subCategory: "television",
            price: 220.99,
            stocks: 10,
            description: "This TV will support MKV format if audio is AAC or MP3 . If the audio format is AC3 (Dolby digital 5.1) Video will play but not audio will not Play. If you use HDMI from laptop almost all format is supported..",
            image: "images/panasonic-1.jpg",
      },
      {
            id: 13,
            name: "Cooking Pan Set Orange & Green",
            category: "kitchen wears",
            subCategory: "cookware",
            price: 230.99,
            stocks: 40,
            description: "Cook an entire meal in your microwave with this M-Cuisine stackable cooking set from Joseph Joseph. Made from BPA-free plastic, it will soon find a permanent place in your kitchen. This set includes a pot, lid, steamer, and griddle. You can cook fish, carrots, and green beans at the same time for a complete healthy meal. A guide that tells you approximate cooking times is included so that you can cook your meal to perfection.",
            image: "images/greenpan-1.jpg",
      },
      {
            id: 14,
            name: "Daneil Klein Original Woman Watch Blue",
            category: "accessories",
            price: 300.99,
            stocks: 8,
            description: "Dial Color: Blue, Case Shape: Round,Band Color: Blue, Band Material: Stainless Steel,Watch Movement Type: Quartz, Watch Display Type: Analog,Case Material: Metal, Case Diameter: 36 millimeters,Water Resistance Depth: 30 meters,1 year manufacturer warranty on manufacturing defects",
            image: "images/w11-1.jpg",
      },
      {
            id: 15,
            name: "Nestle Kitkat Greentea Pack 10pcs",
            category: "snacks & grocery",
            price: 10.99,
            stocks: 200,
            description: "Nestle Kitkat Greentea Pack 10pcs",
            image: "images/kitkat-1-1.jpg",
      },
      {
            id: 16,
            name: "Baby All in Kakoo Grey For Boys",
            category: "kids clothes",
            subCategory: "boy clothes",
            price: 10.99,
            stocks: 50,
            description: "Baby All in Kakoo Grey For Boys collection to warm up your winters! Zip up with this fashionable blend of fleece and fun. Fluffy Winter Fleece Clothing set Faux Fur Hoodie Jacket and Fleece Pant set for kids, has an attached hood a full zip closure in the front.",
            image: "images/kidcl-1.jpg",
      },
      {
            id: 17,
            name: "PS 4 Game MXGP2 Motocross game",
            category: "accessories",
            subCategory: "gaming tools",
            price: 33.99,
            stocks: 20,
            description: "Live the high-octane world of MXGP, featuring the official license, motorbikes, roster and tracks of the 2015 MXGP Championship season. Whether you’re racing to the top of the standings, experiencing the thrill of MXoN or showing your worth on four spectacular indoor tracks, the ride of your life awaits. Don’t forget to create your own team and rider for that added element of personal glory, and enhance the performance of your bike with countless accessories from the biggest brands in motocross.",
            image: "images/psmxgp-1.jpg",
      },
      {
            id: 18,
            name: "Philips coffee maker Espressco star",
            category: "coffee makers",
            price: 250.99,
            stocks: 30,
            description: "2 Slice Capacity Toasting and Grilling Non-stick Plates 750 W Consumption Power Requirement:230 V, 50 Hz Anti skid feet Comfortable front handle for carrying it around.Surely didn’t have a drip coffee machine, and they didn’t have espresso .. our product about the best brewing methods",
            image: "images/aacoffe-1.jpg",
      },
      {
            id: 19,
            name: "Adidas Equipment support Shoes",
            category: "baby & kids",
            subCategory: "shoes & fashion",
            price: 300.99,
            stocks: 50,
            description: "The premium looking Adidas Equipment support Shoes for men crafted with mesh and synthetic which make it lightweight. The breathable mesh offer extended ventilation and comfort. Light strike EVA midsole for best comfort. Full rubber outsole provides durability.",
            image: "images/adidas-2.jpg",
      },
      {
            id: 20,
            name: "Yong Ma Rice Cooker Digital Red",
            category: "kitchen wears",
            subCategory: "cookware",
            price: 130.99,
            stocks: 30,
            description: "Yong Ma Rice Cooker Digital Red",
            image: "images/Untitled-2-1-1.jpg",
      },
      {
            id: 21,
            name: "Paisley Bell Sleeve Women dress",
            category: "kids clothes",
            subCategory: "girl clothes",
            price: 19.66,
            stocks: 100,
            description: "Trendy prints and fabulous silhouettes define this top, chic Cold shoulder sleeve with fine gathers, wear it throughout the day or for a fine dine evening. Team it up with the bottom of your preference and statement Jewelries",
            image: "images/womendress-1.jpg",
      },
      {
            id: 22,
            name: "HTC ONE X android Phone Blue Version",
            category: "accessories",
            subCategory: "android phones",
            price: 399.99,
            stocks: 20,
            description: "HTC ONE X android Phone Blue Version. The smartphone crafted with obsession. You get unprecedented control. Off the chart performance. And innovations like the world’s first dual OIS for pro level photos front and back, as well as end-to-end 24-bit Hi-Res soundInspiration realised in metalIt’s the beauty of light, crafted into a brand new all-metal unibody. Every element of HTC 10 has been designed, refined and perfected. From the bold new chamfered contour to its stunning dual-textured finish and quality construction. All the way down to getting the perfect click from the power button.HTC UltraPixels camerasHTC 10 delivers what may well be the best smartphone camera available today.",
            image: "images/htc-1.jpg",
      },
      {
            id: 23,
            name: "JBL Bluetooth Audio Portable Army Style",
            category: "flash disk drive",
            subCategory: "pen drive",
            price: 164.87,
            stocks: 50,
            description: "The big, bold, beautiful sound of “JBL Bluetooth Audio Portable Army Style” gives adventure a soundtrack. Sound so loud, you’ll have to shout to be heard. It’s an ultra-portable wireless Bluetooth speaker that goes where you go with a stretchy, attachable bungee. You can even attach it to a kayak-it’s totally waterproof.",
            image: "images/jbl-speaker.jpg",
      },
      {
            id: 24,
            name: "Chareles & Keith gold women’s bag",
            category: "accessories",
            price: 130.99,
            stocks: 30,
            description: "Trendy and casual Handbag of Mark & Keith is designed for fashionable woman out there. The handbag is perfect for evening as well as casual outings. Streamline your work- to - weekend carryall with “Charles & keith gold women’s bag” Women Hand Bag.The twin grab handles on the top ensure ease of carrying it all day long, whereas the main zip compartments can easily accommodate all your essential stuff in an organised manner.The back zip pocket is for additional storage, whereas the PU fabric makes it durable and lightweight too.",
            image: "images/bag-1.jpg",
      },
      {
            id: 25,
            name: "PSony Wireless Black Headphone",
            category: "accessories",
            price: 430.99,
            stocks: 100,
            description: "Enjoy industry-leading digital noise cancellation in a headband style wireless headphone. The Smart Listening feature allows you to hear only what you need or want to hear by optimizing your sound based on your activity and surroundings. With the Quick Attention feature, you can have effortless conversations without taking your headphones off.",
            image: "images/area.jpg",
      }
      ,
      {
            id: 26,
            name: "Apple watch nike series 2 red",
            category: "apple products",
            subCategory: "Phone",
            price: 300.99,
            stocks: 50,
            description: "Functions: You Can Use The Smart Watch To Make Or Answer Calls. The Watch’S Built-In Speaker Allows You To Listen To Your Favorite Music Anywhere. Anti-Lost Alarm Function, Push Notifications, Remote Camera. The Watch Has A Sleep Monitor, A Pedometer, A Sedentary Reminder, Water In-Take Reminder. A Stopwatch So It Helps To Keep A Tab On Your Activities. Bluetooth Dialer,Pedometer,Sleep Monitor,Sedentary Reminder,Music Player,Alarm Clock, Watch,Camera,Remote Camera,Bluetooth Sms/Message Notifier,Message Reminder,Call Reminder,Answer Call,Dial Call,Nfc For Quick Pairing. Sync Function: Whats App, Twitter,Facebook;Time,Schedule,Read Message Or News;Entertainment: Mp3,Mp4,Camera.",
            image: "images/wa-1.jpg",
      },
      {
            id: 27,
            name: "Scott solid T-shirt ocean blue",
            category: "kids clothes",
            subCategory: "boy clothes",
            price: 19.98,
            stocks: 30,
            description: "Colour:type4 This tapestry is a new and fashionable home decorative item, designed with fantastic world map pattern. With unique and innovative style, it is an eye-catching and chic tapestry. With versatile uses, it is not only a decorative item, but also an artwork. Buy one and hang it in the living room or bedroom, I am sure that it will add a touch of exotic flavor to your home.",
            image: "images/Untitled-2-2.jpg",
      },
      {
            id: 28,
            name: "Stilettos womens shoes blue",
            category: "accessories",
            price: 199.99,
            stocks: 100,
            description: "Achieve a striking look wearing these sandal by Stilettos. Offering you a comfortable fit and exceptional style. Team up this pair with your favourite outfit to look smart. Make a stylish and trendy addition to your footwear collection with these sandal from Stilettos.",
            image: "images/bl1-1.jpg",
      },
      {
            id: 29,
            name: "Rondell cooking pan aluminium",
            category: "kitchen wears",
            subCategory: "cookware",
            price: 64.98,
            stocks: 150,
            description: "Rondell cooking pan aluminium is a ideal choice for cooking your favorite Dishes.Our products of aluminium cookwares are manufactured with the highest standard aluminium grade. Our perfectly fitted Induction base makes it apt to be used both in Gas Stove and Induction Stove.The body is heavier with comfortable heat resistant handles.These features increase the safety and durability of our products.",
            image: "images/alu1-1.jpg",
      },
      {
            id: 30,
            name: "PlaySation 4 Pro White edition",
            category: "accessories",
            subCategory: "gaming tools",
            price: 610.98,
            stocks: 10,
            description: "Be prepared to Transform your PS4 Controller with the Hytech Plus PS4 God of War Special Edition Theme Feather Soft DualShock 4 Silicone Sleeve. This skin is better than plain silicone skins since they are much softer and look amazing. At the same time the high quality silicone gives you excellent grip and has an amazing feel. Also, the ribbed back gives the controller a very grippy feel. You will actually want to hold the controller for longer with this skin on. Premium Quality Soft Silicone Material Provides A More Comfortable Experience And Can Allow You To Play For Longer. You can never go wrong with us!",
            image: "images/ps4white-1.jpg",
      }
]


export const allCategories = ["accessories", "baby & kids", "kitchen wears", "home living", "snacks & grocery", "kids clothes"]